# Generated by Django 5.0.3 on 2024-03-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_time_alter_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='time',
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=7000, null=True),
        ),
    ]
